// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNwUhMtWW1hEKEF2gKPdFf-PM1-275aQ0',
    appId: '1:824013898397:web:be5553e5b4e2f0bf04ca74',
    messagingSenderId: '824013898397',
    projectId: 'foodorderingapp-e5121',
    authDomain: 'foodorderingapp-e5121.firebaseapp.com',
    storageBucket: 'foodorderingapp-e5121.appspot.com',
    measurementId: 'G-C95KG3L15X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2JQVbiNc_y9RDMdR1QezeRnwB-977o0',
    appId: '1:824013898397:android:91945a026cb766d304ca74',
    messagingSenderId: '824013898397',
    projectId: 'foodorderingapp-e5121',
    storageBucket: 'foodorderingapp-e5121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJM2Sh4Ywh3W_jIIGi8RvWcdDAgwcffBs',
    appId: '1:824013898397:ios:be2372752a0d72a104ca74',
    messagingSenderId: '824013898397',
    projectId: 'foodorderingapp-e5121',
    storageBucket: 'foodorderingapp-e5121.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJM2Sh4Ywh3W_jIIGi8RvWcdDAgwcffBs',
    appId: '1:824013898397:ios:6870571d0037b4f404ca74',
    messagingSenderId: '824013898397',
    projectId: 'foodorderingapp-e5121',
    storageBucket: 'foodorderingapp-e5121.appspot.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
